config/routes.rb
Smswebapp::Application.routes.draw do
  get "search/create"

  resources :synchashes
  resources :outmessages
  resources :messages
  resources :users
  resources :devices

  match "login" => "auth#login"
  match "logout" => "auth#logout"
  match "mlogin" => "auth#mobile_login"
  match "signup" => "users#new"
  match "search" => "search#lookfor"

  root :to => 'home#index'

end

app/models/synchash.rb
class Synchash < ActiveRecord::Base
  belongs_to :user

  private
  validates :user_id, :uniqueness => true, :presence => true
end

app/controllers/synchashes_controller.rb
class SynchashesController < ApplicationController
  skip_before_filter :ensure_user_logged_in, :only => [:create, :update]
  # GET /synchashes
  # GET /synchashes.json
  def index
    @synchashes = Synchash.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @synchashes }
    end
  end

  # GET /synchashes/1
  # GET /synchashes/1.json
  def show
    @synchash = Synchash.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @synchash }
    end
  end

  # GET /synchashes/new
  # GET /synchashes/new.json
  def new
    @synchash = Synchash.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @synchash }
    end
  end

  # GET /synchashes/1/edit
  def edit
    @synchash = Synchash.find(params[:id])
  end

  # POST /synchashes
  # POST /synchashes.json
  def create
    user = User.find_by_username(params[:username])
    newIn = false;
    newOut = false;

    if !user.nil?
      synchash = user.synchash
      #If the user has a synchash already
      if !synchash.nil?
        newIn = !synchash.in_hash.eql?(params[:in_hash]) if !params[:in_hash].eql?("empty")
        newOut = !synchash.out_hash.eql?(params[:out_hash]) if !params[:out_hash].eql?("empty")
        render_output(synchash,newIn,newOut)
      else
        #otherwise the user is new! We need to sync everything from their device so set a default hash
        synchash = Synchash.new
        synchash.in_hash = "empty"
        synchash.out_hash = "empty"
        synchash.user = user
        synchash.save
        render_output(synchash,true,true)
      end
    end
  end

  # PUT /synchashes/1
  # PUT /synchashes/1.json
  def update
    user = User.find_by_username(params[:username])
    synchash = user.synchash

    #if the user has a synchash, update it
    if !synchash.nil?
      synchash.in_hash = params[:in_hash] if params[:in_status]
      synchash.out_hash = params[:out_hash] if params[:out_status]
    else
    #otherwise the user is new and has somehow skipped the inital sync. No matter, let's set it up now!
      synchash = Synchash.new
      synchash.in_hash = "empty"
      synchash.out_hash = "empty"
      synchash.in_hash = params[:in_hash] if params[:in_status]
      synchash.out_hash = params[:out_hash] if params[:out_status]
      synchash.user = user
    end
    if (synchash.save)
      render :json => {:status => 1}
    else
      render :json => {:status => 0}
    end
  end

  # DELETE /synchashes/1
  # DELETE /synchashes/1.json
  def destroy
    @synchash = Synchash.find(params[:id])
    @synchash.destroy

    respond_to do |format|
      format.html { redirect_to synchashes_url }
      format.json { head :ok }
    end
  end

  private
  def render_output(synchash,newIn,newOut)
    if (newIn || newOut)
      render :json => {:sync_status => 1, :new_in_status => newIn, :new_out_status => newOut, :in_hash => synchash.in_hash, :out_hash => synchash.out_hash}
    else
      render :json => {:sync_status => 0}
    end
  end
end

app/helpers/synchashes_helper.rb
module SynchashesHelper
end

app/views/synchashes/_form.html.erb
<%= form_for(@synchash) do |f| %>
  <% if @synchash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@synchash.errors.count, "error") %> prohibited this synchash from being saved:</h2>

      <ul>
      <% @synchash.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :in_hash %><br />
    <%= f.text_field :in_hash %>
  </div>
  <div class="field">
    <%= f.label :out_hash %><br />
    <%= f.text_field :out_hash %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/synchashes/edit.html.erb
<h1>Editing synchash</h1>

<%= render 'form' %>

<%= link_to 'Show', @synchash %> |
<%= link_to 'Back', synchashes_path %>

app/views/synchashes/index.html.erb
<h1>Listing synchashes</h1>

<table>
  <tr>
    <th>In hash</th>
    <th>Out hash</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @synchashes.each do |synchash| %>
  <tr>
    <td><%= synchash.in_hash %></td>
    <td><%= synchash.out_hash %></td>
    <td><%= synchash.user %></td>
    <td><%= link_to 'Show', synchash %></td>
    <td><%= link_to 'Edit', edit_synchash_path(synchash) %></td>
    <td><%= link_to 'Destroy', synchash, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Synchash', new_synchash_path %>

app/views/synchashes/new.html.erb
<h1>New synchash</h1>

<%= render 'form' %>

<%= link_to 'Back', synchashes_path %>

app/views/synchashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>In hash:</b>
  <%= @synchash.in_hash %>
</p>

<p>
  <b>Out hash:</b>
  <%= @synchash.out_hash %>
</p>

<p>
  <b>User:</b>
  <%= @synchash.user %>
</p>


<%= link_to 'Edit', edit_synchash_path(@synchash) %> |
<%= link_to 'Back', synchashes_path %>