config/routes.rb
Smswebapp::Application.routes.draw do
  get "search/create"

  resources :synchashes
  resources :outmessages
  resources :messages
  resources :users
  resources :devices

  match "login" => "auth#login"
  match "logout" => "auth#logout"
  match "mlogin" => "auth#mobile_login"
  match "signup" => "users#new"
  match "search" => "search#lookfor"

  root :to => 'home#index'

end

app/models/outmessage.rb
class Outmessage < ActiveRecord::Base
  belongs_to :user
end

app/controllers/outmessages_controller.rb
class OutmessagesController < ApplicationController
skip_before_filter :ensure_user_logged_in, :only => [:create, :show]
  # GET /outmessages
  # GET /outmessages.json
  def index
    @outmessages = Outmessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @outmessages }
    end
  end

  # GET /outmessages/1
  # GET /outmessages/1.json
  def show
    @outmessage = Outmessage.find(params[:id])
    respond_to do |format|
      format.html {
        render :layout => false
      }# show.html.erb
      format.json { 
        render :json => @outmessage

        message = Message.new
        message.origin = "DEVICE"
        message.message = @outmessage.message
        message.timestamp = (Time.now.to_i)*1000
        message.user = @outmessage.user
        message.destination = @outmessage.destination
        message.save

        @outmessage.destroy }
    end
  end

  # GET /outmessages/new
  # GET /outmessages/new.json
  def new
    @outmessage = Outmessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @outmessage }
    end
  end

  # GET /outmessages/1/edit
  def edit
    @outmessage = Outmessage.find(params[:id])
  end

  # POST /outmessages
  # POST /outmessages.json
  def create
    @outmessage = Outmessage.new
    @outmessage.destination = params[:outmessage][:destination]
    @outmessage.message = params[:outmessage][:message]
    @outmessage.user = User.find_by_username(session[:user_id].username)

    if @outmessage.save
      if (params[:ajax_request])
        render :layout => false
      end
      notify_push_user(@outmessage)
    end
  end

  # PUT /outmessages/1
  # PUT /outmessages/1.json
  def update
    @outmessage = Outmessage.find(params[:id])

    respond_to do |format|
      if @outmessage.update_attributes(params[:outmessage])
        format.html { redirect_to @outmessage, :notice => 'Outmessage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @outmessage.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /outmessages/1
  # DELETE /outmessages/1.json
  def destroy
    @outmessage = Outmessage.find(params[:id])
    @outmessage.destroy

    respond_to do |format|
      format.html { redirect_to outmessages_url }
      format.json { head :ok }
    end
  end

  private
  def notify_push_user(outmessage)
    C2DM.authenticate!("sdnotifications@gmail.com", "GlazingPutty", "smswebapp")
    c2dm = C2DM.new

    notification = {
      :registration_id => session[:user_id].devices[0].reg_id, 
      :data => {
        :action => "NEW_SMS_TO_SEND",
        :msg_id => outmessage.id
      }
    }

    c2dm.send_notification(notification)
  end
end

app/helpers/outmessages_helper.rb
module OutmessagesHelper
end

app/views/outmessages/_form.html.erb
<%= form_for(@outmessage) do |f| %>
  <% if @outmessage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outmessage.errors.count, "error") %> prohibited this outmessage from being saved:</h2>

      <ul>
      <% @outmessage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outmessages/create.html.erb
<%= @outmessage.id %>

app/views/outmessages/edit.html.erb
<h1>Editing outmessage</h1>

<%= render 'form' %>

<%= link_to 'Show', @outmessage %> |
<%= link_to 'Back', outmessages_path %>

app/views/outmessages/index.html.erb
<h1>Listing outmessages</h1>

<table>
  <tr>
    <th>Destination</th>
    <th>Message</th>
    <th>Timestamp</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outmessages.each do |outmessage| %>
  <tr>
    <td><%= outmessage.destination %></td>
    <td><%= outmessage.message %></td>
    <td><%= outmessage.timestamp %></td>
    <td><%= outmessage.user %></td>
    <td><%= link_to 'Show', outmessage %></td>
    <td><%= link_to 'Edit', edit_outmessage_path(outmessage) %></td>
    <td><%= link_to 'Destroy', outmessage, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outmessage', new_outmessage_path %>

app/views/outmessages/new.html.erb
<h1>New outmessage</h1>

<%= render 'form' %>

<%= link_to 'Back', outmessages_path %>

app/views/outmessages/show.html.erb
<p class="msg msg-to"><%= @outmessage.message %><small><br/>Waiting for device to send...</small></p>